apiVersion: v1
kind: Pod
metadata:
  name: todo-db-init
  namespace: project
spec:
  containers:
    - name: todo-db-init
      image: postgres:13
      command: 
        - sh
        - -c
        - |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h todo-db-svc -U ${POSTGRES_USER}; do
            echo "PostgreSQL is unavailable - sleeping"
            sleep 2
          done
          echo "PostgreSQL is ready!"
          echo "Creating todos table..."
          psql -h todo-db-svc -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<-EOSQL
            CREATE TABLE IF NOT EXISTS todos (
              id SERIAL PRIMARY KEY,
              text TEXT NOT NULL,
              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            );
          EOSQL
          echo "Database initialized successfully!"
          sleep infinity
      env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: todo-backend-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-db-secret
              key: POSTGRES_PASSWORD
  restartPolicy: Never
